### ISSUE TITLE
Client Side Error

### ISSUE THREAD

**Issue by lgrones** [pgr3931/manga-overview#6]
TypeError: Cannot set properties of undefined (setting 'hasNewVolume')
    at useInitialization.tsx:105:19
    at No (react-dom.production.min.js:169:46)
    at zo (react-dom.production.min.js:170:451)
    at Object.useState (react-dom.production.min.js:186:528)
    at n.useState (react.production.min.js:25:394)
    at We (useInitialization.tsx:40:39)
    at Fe (home.tsx:33:23)
    at Eo (react-dom.production.min.js:167:137)
    at Pu (react-dom.production.min.js:197:258)
    at xi (react-dom.production.min.js:292:88)

**Comment by lgrones** [comment]
Fixed with 141ccff840a336b625e2afd2efae77293d6656fe
